server:
  port: 80

zuul:
  routes:
    uaa:
      path: /uaa/**
      url: http://localhost:8001
    user:
      path: /api/user/**
      url: http://localhost:8010
  add-proxy-headers: true
  host:
    connect-timeout-millis: 5000
  sensitive-headers:

security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:8001/oauth/token_key
      id: gateway
    client:
      client-id: gateway
      client-secret: 123456
      grant-type: client_credentials

logging:
  level:
    root: info
    org:
      springframework:
        security: DEBUG
        social: DEBUG
