server:
  port: 80

spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    #连接池及重试配置，防止mysql如果8小时自动断开连接问题
    tomcat:
      max-active: 100
      min-idle: 10
      min-evictable-idle-time-millis:  1800000
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      validation-query: select 1
  redis:
    host: 127.0.0.1

app:
  security:
    # 白名单 （未登录用户可访问）
    whitelist: /user/register,/verification/sms,/verification/captcha
    # 验证码配置 参见VerificationProperties
    verification:
      #图片验证码配置项，参见ImageCodeProperties
      captcha:
        length: 4
        width: 100
        height: 30
        expireIn: 30
        # 配置需要图形验证码验证的url, 两个验证码如果配的url中相同部分则短信优先级要高
        url:
      #短信验证码配置项，参见SmsCodeProperties
      sms:
        # 短信验证码登录处理的url
        loginProcessesUrl: /oauth/connect
        length: 6
        expireIn: 60
        # 配置需要短信验证码验证的url
        url:

    #社交登录功能拦截的url,参见SocialProperties
    connect:
      #      signUpUrl:
      #QQ登录配置，参见QQProperties
      qq:
        appId:
        appSecret:
        providerId: qq
      #微信登录配置
      weixin:
        appId: wxd99431bbff8305a0
        appSecret: 60f78681d063590a469f1b297feff3c4
        providerId: weixin

    #认证服务器注册的第三方应用配置项，参见OAuth2ClientProperties
    oauth2:
      # 第三方客户端配置
      clients:
        - clientId: app
          accessTokenValidateSeconds: 3600
          refreshTokenValidateSeconds: 2592000
        - clientId: test
      #OAuth2认证服务器的tokenStore的类型，可选值为redis和jwt，值为jwt时发出的token为jwt
      tokenStore: jwt
      #使用jwt时为token签名的秘钥
      jwtSigningKey: aXo3t%12_Ao

logging:
  level:
    root: info
    org:
      springframework:
        security: DEBUG
        social: DEBUG

---
spring:
  profiles: browser
app:
  security:
    #浏览器环境配置项，参见BrowserProperties
    browser:
      # 登录地址
      signInUrl: /signIn.html
      # 登录提交地址
      signInProcessingUrl: /login/form
      # 登录成功地址
      singInSuccessUrl: /index.html
      # 注册地址
      signUpUrl: /signUp.html
      # 退出处理地址
      signOutProcessingUrl: /logout
      # 退出成功地址
      signOutSuccessUrl: /signIn.html
      # 响应类型，REDIRECT页面传统跳转，vue、react api请求方式
      responseType: REDIRECT
      #session管理相关配置，参见SessionProperties
      session:
        maximumSessions: 1
        maxSessionsPreventsLogin: false
        sessionInvalidUrl: /session-invalid.html

    verification:
      #短信验证码配置项
      sms:
        # 短信验证码登录处理的url
        loginProcessesUrl: /login/phone
    connect:
      #社交登录功能拦截的url
      filterProcessesUrl: /login/connect
---
